### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by snotskie** [EducationalSciences693/ShadowspectRandomForest#2]
- [ ] NA imputation - if an NA should be a zero, make it a zero
- [ ] define and justify what we mean by fair, valid
- [x] means and SDs for sri for each subgroup, sbst

**Comment by snotskie** [comment]
Dalex fairness metrics are defined by barocas in https://fairmlbook.org/

We are failing the independence metric, formally:
$$\hat y \perp G$$
or
$$P(\hat y \mid G) = P(\hat y)$$.
That is, the distribution of the predicted values is substantively (even if not significantly) different across genders, resulting in disparate outcomes.

However, we do pass the separation metric, formally:
$$\hat y \perp G \mid y$$
or
$$P(\hat y \mid G, y) = P(\hat y \mid y)$$.
That is, even though the distribution of the predicted values is substantively different across genders, so too were the true values, avoiding (to the extent measured here) disparate treatment.
